"""add unique constraint on cart_item cart_id product_id

Revision ID: a935db5feb4e
Revises: 98c93661a8f1
Create Date: 2026-09-11 07:16:06.530082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a935db5feb4e'
down_revision: Union[str, Sequence[str], None] = '98c93661a8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cart_product', 'cart_item', ['cart_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cart_product', 'cart_item', type_='unique')
    # ### end Alembic commands ###
